export const ROLE_VALUES = [
  'admin',
  'director',
  'general_director',
  'financer',
  'chief_accountant',
  'lawyer',
  'security',
  'secretary',
  'manager_sales',
  'head_sales',
  'manager_ktk_vvo',
  'head_ktk_vvo',
  'manager_ktk_mow',
  'head_ktk_mow',
  'head_hr',
  'hr_specialist',
  'garage_head_vvo',
  'garage_head',
  'manager_auto',
  'manager_rail',
  'manager_extra',
  'manager_to',
  'warehouse_manager',
  'warehouse_keeper',
] as const;

export type RoleValue = typeof ROLE_VALUES[number];
