export const ROLE_VALUES = [
  'admin',
  'director',
  'general_director',
  'financer',
  'chief_accountant',
  'deputy_chief_accountant',
  'lawyer',
  'security',
  'secretary',
  'manager_sales',
  'head_sales',
  'manager_ktk_vvo',
  'head_ktk_vvo',
  'manager_ktk_mow',
  'head_ktk_mow',
  'head_hr',
  'hr_specialist',
  'hr_recruiter',
  'garage_head_vvo',
  'manager_auto',
  'manager_rail',
  'manager_extra',
  'warehouse_manager_vvo',
  'warehouse_keeper',
  'counterparty_user',
  'bdd_specialist_vvo',
  'bdd_specialist_mow',
  'dispatcher_vvo',
] as const;

export type RoleValue = typeof ROLE_VALUES[number];
